# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a4c81e04ac172c7d76e408ead0af294f436c7e27d8b6bf2cd172c4f648bc46c562b0e9e446311868cd53b1a6010d2921b22397d76a72512f6a10c4a07f2a002

test:
  secret_key_base: 8c99860ef96bc1421665641e76e4989e56a0640b5c298c31d502fa8f26516f09c0760812e723175f0b48f7504acfbd2f0ceacbb8e823db53be926e97d298af6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
